######################################################################
# Automatically generated by qmake (3.0) jeu. mai 1 18:05:34 2014
######################################################################

TEMPLATE = app
TARGET = audioplayer
INCLUDEPATH += . src

# Input
HEADERS += src/audiofile.h src/audioplayer.h
SOURCES += src/audiofile.cpp src/audioplayer.cpp src/main.cpp
